theme: jekyll-theme-architect

title: Answering the QLUE
description: >-
  Unqualified search for an answer to the Question of Life, Universe, and Everything.
baseurl: "/seeker"
url: "https://kvark.github.io"

permalink: /:title

author:
  name: "kvark"
  email: "kvark at fastmail com"
  url: "https://kvark.github.io"