name: check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1

    - name: Select Rust channel
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable

    - name: Check Basics
      run: cargo check --workspace --no-default-features

    - name: Test All
      run: cargo test --workspace --all-features
